//EIBKCTRL JOB MSGCLASS=X,MSGLEVEL=(1,1),REGION=64M,NOTIFY=&SYSUID      JOB29240
//*---------------------------------------------------------------------
//* BANK CONTROL
//*---------------------------------------------------------------------
//EIBKCTRL EXEC SAS609
//OCCUP    DD DISP=SHR,DSN=RBP2.B033.BANKCTRL.OCCUP
//MISC     DD DISP=SHR,DSN=RBP2.B033.UNLOAD.CUSTMSCD.DESC(0)
//BKCTRL   DD DISP=OLD,DSN=SAP.PBB.BANK.CONTROL
//SYSIN    DD *

OPTIONS YEARCUTOFF=1960 NODATE NONUMBER NOCENTER;

DATA BKCTRL.OCCUP;
   INFILE OCCUP;
   INPUT @011 START        $3.  /* OCCUPAT     */
         @015 LABEL       $25.  /* DESCRIPTION */
         ;
   TYPE    = 'C';
   FMTNAME = 'OCCUPFMT';
RUN;
PROC SORT DATA=BKCTRL.OCCUP NODUPKEY; BY START; RUN;

DATA BKCTRL.MISC;
   INFILE MISC;
   INPUT @005 DEMONO       $2.
         @008 DEMOCODE    $10.  /* DEMOCODE    */
         @019 ENTRYDATE    $7.
         @027 EFFECTDATE  $13.
         @041 DELIND       $1.
         @043 LABEL       $20.  /* DESCRIPTION */
         ;
   IF DEMONO = '08' THEN DO;
      START   = SUBSTR(DEMOCODE,2,2);
      TYPE    = 'C';
      FMTNAME = 'BGCFMT';
   END;
RUN;
PROC SORT DATA=BKCTRL.MISC NODUPKEY; BY DEMONO DEMOCODE START; RUN;

DATA BKCTRL.CISFMT;
   FORMAT START $10. LABEL $100. FMTNAME $30.;
   SET BKCTRL.OCCUP BKCTRL.MISC;
   WHERE FMTNAME NE '';
   KEEP START TYPE LABEL FMTNAME;
RUN;
PROC SORT; BY FMTNAME START; RUN;
PROC FORMAT LIBRARY=WORK CNTLIN=BKCTRL.CISFMT; RUN;
