//EIIWOF02 JOB MISEIS,EIFWOFFA,MSGCLASS=A,MSGLEVEL=(1,1),CLASS=A,       JOB08445
//         NOTIFY=&SYSUID
//* **********************************************
//*   UPLOAD FROM TEXT FILE PROVIDE BY CCD
//*   (A/C TO BE WRITE OFF)
//* **********************************************
//EIIWOF02 EXEC SAS609
//*WOFF    DD DSN=OPER.RESTORE.PBB.NPL.HP.WOFF01.TXT,DISP=SHR
//*WOFF    DD DSN=SAP.PBB.IWAPPR.TXT,DISP=SHR
//WOFF     DD DSN=RBP2.B033.LN.WRI2.OFF.MIS,DISP=SHR
//NPL      DD DSN=SAP.PIBB.NPL.HP.SASDATA.WOFF,DISP=OLD
//SYSIN    DD *
OPTIONS YEARCUTOFF=1950 NOCENTER;

  *** UPLOAD FROM TEXT FILE PROVIDE BY CCD ***;
  *** CHECK THE POSITION OF EACH FIELDS    ***;

DATA NPL.WOFFHP(KEEP=ACCTNO);
  INFILE WOFF;
  INPUT @142  ACCTNO   10.
        @236  COSTCTR   4.
        ;
  IF ((3000<=COSTCTR<=3999) OR COSTCTR IN (4043,4048));
RUN;
PROC SORT; BY ACCTNO;
PROC PRINT;


             //EIIWOF03  JOB MISEIS,EIFMNPL0,COND=(0,LT),CLASS=A,MSGCLASS=X,
//         NOTIFY=&SYSUID
//*
//*%OPC SCAN
//*%OPC SETFORM OCDATE=(DD)
//*%OPC SETFORM OCLASTC=(DD)
//*
/* ***********************************************
/* ORIGINAL FROM EIFMNPLE
/* ***********************************************
//EIIWOF03 EXEC SAS609
//*
//*%OPC BEGIN ACTION=INCLUDE,
//*%OPC COMP=(&OCDATE..EQ.(01,02,03,04,05,06,07))
//*LOAN     DD DSN=SAP.PIBB.MNILN(0),DISP=SHR
//*%OPC END ACTION=INCLUDE
//*
//*%OPC BEGIN ACTION=INCLUDE,
//*%OPC COMP=((&OCDATE..NE.(01)),
//*%OPC       (&OCDATE..NE.(02)),
//*%OPC       (&OCDATE..NE.(03)),
//*%OPC       (&OCDATE..NE.(04)),
//*%OPC       (&OCDATE..NE.(05)),
//*%OPC       (&OCDATE..NE.(06)),
//*%OPC       (&OCDATE..NE.(07)))
//LOAN     DD DSN=SAP.PIBB.MNILN.DAILY(0),DISP=SHR
//*%OPC END ACTION=INCLUDE
//*
//NPL6     DD DSN=SAP.PIBB.NPL.HP.SASDATA.WOFF,DISP=OLD
//SORTWK01 DD UNIT=SYSDA,SPACE=(CYL,(500))
//SORTWK02 DD UNIT=SYSDA,SPACE=(CYL,(500))
//SORTWK03 DD UNIT=SYSDA,SPACE=(CYL,(500))
//SORTWK04 DD UNIT=SYSDA,SPACE=(CYL,(500))
//SYSIN    DD DSN=SAP.BNM.PROGRAM(EIFMNP02),DISP=SHR
