//EIIWOF02 JOB MISEIS,EIFWOFFA,MSGCLASS=A,MSGLEVEL=(1,1),CLASS=A,       JOB08445
//         NOTIFY=&SYSUID
//* **********************************************
//*   UPLOAD FROM TEXT FILE PROVIDE BY CCD
//*   (A/C TO BE WRITE OFF)
//* **********************************************
//EIIWOF02 EXEC SAS609
//*WOFF    DD DSN=OPER.RESTORE.PBB.NPL.HP.WOFF01.TXT,DISP=SHR
//*WOFF    DD DSN=SAP.PBB.IWAPPR.TXT,DISP=SHR
//WOFF     DD DSN=RBP2.B033.LN.WRI2.OFF.MIS,DISP=SHR
//NPL      DD DSN=SAP.PIBB.NPL.HP.SASDATA.WOFF,DISP=OLD
//SYSIN    DD *
OPTIONS YEARCUTOFF=1950 NOCENTER;

  *** UPLOAD FROM TEXT FILE PROVIDE BY CCD ***;
  *** CHECK THE POSITION OF EACH FIELDS    ***;

DATA NPL.WOFFHP(KEEP=ACCTNO);
  INFILE WOFF;
  INPUT @142  ACCTNO   10.
        @236  COSTCTR   4.
        ;
  IF ((3000<=COSTCTR<=3999) OR COSTCTR IN (4043,4048));
RUN;
PROC SORT; BY ACCTNO;
PROC PRINT;
