//EIMNFISS JOB MISEIS,EIBMTH1A,MSGCLASS=A,CLASS=A,NOTIFY=&SYSUID,
//         USER=OPCC
//*
//DELETE   EXEC PGM=IEFBR14
//DD1      DD DISP=(MOD,DELETE,DELETE),
//            SPACE=(TRK,(1,10)),
//            DSN=SAP.NFISS.TEMP
//DD2      DD DISP=(MOD,DELETE,DELETE),
//            SPACE=(TRK,(1,10)),
//            DSN=SAP.NFISS.TEMP.FTP
//CREATE   EXEC PGM=IEFBR14
//CRT01    DD DSN=SAP.NFISS.TEMP.FTP,
//            DISP=(NEW,CATLG,DELETE),
//            DCB=(RECFM=FB,LRECL=80,BLKSIZE=24000),
//            SPACE=(CYL,(200,200),RLSE),UNIT=(SYSDA,5)
//EIMNFISS  EXEC SAS609,REGION=8M,WORK='250000,200000'
//BT        DD DSN=SAP.BT.FISS,DISP=SHR
//IBT       DD DSN=SAP.IBT.FISS,DISP=SHR
//TEMP      DD DSN=SAP.NFISS.TEMP,DISP=(NEW,DELETE,DELETE),
//             DCB=(RECFM=FS,LRECL=27648,BLKSIZE=27648),
//             SPACE=(CYL,(100,50)),UNIT=(SYSDA,5)
//PGM       DD DSN=SAP.BNM.PROGRAM,DISP=SHR
//SASLIST   DD SYSOUT=X
//SYSIN     DD *

OPTIONS SORTDEV=3390 YEARCUTOFF=1950 LS=132 PS=60 NOCENTER;

DATA REPTDATE (KEEP=REPTDATE);
  REPTDATE=INPUT('01'||PUT(MONTH(TODAY()), Z2.)||
                 PUT(YEAR(TODAY()), 4.), DDMMYY8.)-1;
  SELECT(DAY(REPTDATE));
    WHEN (8)  DO; SDD = 1;  WK = '1'; WK1 = '4'; END;
    WHEN(15)  DO; SDD = 9;  WK = '2'; WK1 = '1'; END;
    WHEN(22)  DO; SDD = 16; WK = '3'; WK1 = '2'; END;
    OTHERWISE DO; SDD = 23; WK = '4'; WK1 = '3';
                            WK2= '2'; WK3 = '1'; END;
  END;
  MM = MONTH(REPTDATE);
  IF WK = '1' THEN DO;
     MM1 = MM - 1;
     IF MM1 = 0 THEN MM1 = 12;
  END;
  ELSE MM1 = MM;
  MM2 = MM - 1;
  IF MM2 = 0 THEN MM2 = 12;
  CALL SYMPUT('NOWK',PUT(WK,$1.));
  CALL SYMPUT('NOWK1',PUT('1',$1.));
  CALL SYMPUT('NOWK2',PUT('2',$1.));
  CALL SYMPUT('NOWK3',PUT('3',$1.));
  CALL SYMPUT('REPTMON',PUT(MM,Z2.));
  CALL SYMPUT('REPTMON1',PUT(MM1,Z2.));
  CALL SYMPUT('REPTMON2',PUT(MM2,Z2.));
  CALL SYMPUT('REPTYEAR',PUT(REPTDATE,YEAR4.));
  CALL SYMPUT('REPTDAY',PUT(DAY(REPTDATE),Z2.));
  CALL SYMPUT('RDATE',PUT(REPTDATE,DDMMYY8.));
  CALL SYMPUT('TDATE',REPTDATE);
RUN;

LIBNAME LN  "SAP.PBB.D&REPTYEAR" DISP=SHR;
LIBNAME ILN "SAP.PIBB.D&REPTYEAR" DISP=SHR;

DATA TEMP.LN_UTIL; SET LN.B80510; RUN;
DATA TEMP.LN_UNUTIL; SET LN.B80200; RUN;
DATA TEMP.ILN_UTIL; SET ILN.B80510; RUN;
DATA TEMP.ILN_UNUTIL; SET ILN.B80200; RUN;
DATA TEMP.BT_UTIL; SET BT.B80510; RUN;
DATA TEMP.BT_UNUTIL; SET BT.B80200; RUN;
DATA TEMP.IBT_UTIL; SET IBT.B80510; RUN;
DATA TEMP.IBT_UNUTIL; SET IBT.B80200; RUN;

FILENAME TRANFILE 'SAP.NFISS.TEMP.FTP' DISP=OLD;
PROC CPORT LIBRARY=TEMP FILE=TRANFILE;

//******************************************************************
//* FTP HOST DATASETS TO EDW
//******************************************************************
//RUNSFTP  EXEC COZBATCH
//CMD.SYSUT1 DD DISP=SHR,DSN=OPER.PBB.PARMLIB(EDW#SFTP)
//           DD *
lzopts servercp=$servercp,notrim,overflow=trunc,mode=binary
lzopts linerule=$lr
cd /stgsrcsys/host/ftpfiles
PUT //SAP.NFISS.TEMP.FTP  UTNFFTP
lzopts servercp=$servercp,notrim,overflow=trunc,mode=text
lzopts linerule=$lr
cd /stgsrcsys/host/control
PUT //SAP.CRMS.DAY.CONTROL UTNFISS.TXT
EOB
/*
